//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrickWorks
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brick
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Brick()
        {
            this.BrickCosts = new HashSet<BrickCost>();
            this.ManufacturedBricks = new HashSet<ManufacturedBrick>();
            this.OrderedBricks = new HashSet<OrderedBrick>();
        }
    
        public int Id { get; set; }
        public string Mark { get; set; }
        public Nullable<float> Height { get; set; }
        public Nullable<float> Lenght { get; set; }
        public Nullable<float> Weight { get; set; }
        public string Parameters { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BrickCost> BrickCosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManufacturedBrick> ManufacturedBricks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderedBrick> OrderedBricks { get; set; }
    }
}
