//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrickWorks
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrickCost
    {
        public int Id { get; set; }
        public int BrickId { get; set; }
        public System.DateTime Date { get; set; }
        public float Cost { get; set; }
    
        public virtual Brick Brick { get; set; }
    }
}
