//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrickWorks
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bwksEntities : DbContext
    {
        public bwksEntities()
            : base("name=bwksEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BrickCost> BrickCosts { get; set; }
        public virtual DbSet<Brick> Bricks { get; set; }
        public virtual DbSet<Building> Buildings { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<DeliveryCost> DeliveryCosts { get; set; }
        public virtual DbSet<ManufacturedBrick> ManufacturedBricks { get; set; }
        public virtual DbSet<OrderedBrick> OrderedBricks { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<WallSize> WallSizes { get; set; }
        public virtual DbSet<ordersView> ordersViews { get; set; }
    }
}
